In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import GridSearchCV, train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv('task_d.csv')
data.head()

x         y         z       x*x       2*y  2*z+3*x*x         w  \
0 -0.581066  0.841837 -1.012978 -0.604025  0.841837  -0.665927 -0.536277   
1 -0.894309 -0.207835 -1.012978 -0.883052 -0.207835  -0.917054 -0.522364   
2 -1.207552  0.212034 -1.082312 -1.150918  0.212034  -1.166507  0.205738   
3 -1.364174  0.002099 -0.943643 -1.280666  0.002099  -1.266540 -0.665720   
4 -0.737687  1.051772 -1.012978 -0.744934  1.051772  -0.792746 -0.735054   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [4]:
X = data.drop(labels = ['target'], axis = 1).values
X[:3]

array([[-0.5810659 ,  0.84183714, -1.01297765, -0.60402468,  0.84183714,
        -0.66592679, -0.53627703],
       [-0.89430898, -0.2078351 , -1.01297765, -0.88305213, -0.2078351 ,
        -0.91705408, -0.52236404],
       [-1.20755205,  0.21203379, -1.08231219, -1.15091848,  0.21203379,
        -1.16650718,  0.20573767]])

In [5]:
scaler = StandardScaler()

In [6]:
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [7]:
X_std = scaler.transform(X)

In [8]:
Y = data.target.values

In [9]:
"""
d_train_n = d_train after adding noise (10^-2)
"""
X_std_n = np.add(X_std, 10 ** -2) 
X_std_n[:5]

array([[-0.5710659 ,  0.85183714, -1.00297765, -0.59402468,  0.85183714,
        -0.65592679, -0.52627703],
       [-0.88430898, -0.1978351 , -1.00297765, -0.87305213, -0.1978351 ,
        -0.90705408, -0.51236404],
       [-1.19755205,  0.22203379, -1.07231219, -1.14091848,  0.22203379,
        -1.15650718,  0.21573767],
       [-1.35417359,  0.01209934, -0.93364311, -1.27066624,  0.01209934,
        -1.25653955, -0.65571996],
       [-0.72768744,  1.06177159, -1.00297765, -0.73493354,  1.06177159,
        -0.78274607, -0.72505412]])

In [10]:
D_Train, d_test, Y_Train, y_test = train_test_split(X_std_n, Y, test_size = 0.2, random_state = 42, stratify = Y)

In [11]:
d_train, d_cv, y_train, y_cv = train_test_split(D_Train, Y_Train, test_size = 0.2, random_state = 52, stratify = Y_Train)

In [12]:
best_model = LogisticRegression(C = 1e-10, class_weight = {1: 0.5, 0: 0.5},
                   penalty = 'l2', solver = 'liblinear',
                   tol = 0.001, random_state = 21,
                    max_iter = 500, n_jobs = -1
                  )

In [13]:
best_model.fit(d_train, y_train)

C:\Users\mistertandon\Anaconda3\envs\applied-ai\lib\site-packages\sklearn\linear_model\_logistic.py:1539: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 8.
  " = {}.".format(effective_n_jobs(self.n_jobs)))


LogisticRegression(C=1e-10, class_weight={0: 0.5, 1: 0.5}, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=500, multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=21, solver='liblinear', tol=0.001, verbose=0,
                   warm_start=False)

In [14]:
best_model.coef_

array([[ 1.15899937e-09, -1.13364602e-09,  1.52535990e-09,
         1.12510844e-09, -1.13364602e-09,  1.19676802e-09,
         8.56610605e-10]])

In [15]:
y_test_hat = best_model.predict(d_test)
accuracy_score(y_test, y_test_hat)

1.0